version: "3"
services:
  lb-server:
    build: ./lb-server
    ports:
      - "4200:4200"
    networks:
      - app-network
    restart: always

  server1:
    build: ./server
    networks:
      - app-network

  server2:
    build: ./server
    networks:
      - app-network
  
  server3:
    build: ./server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge