version: "3"
services:
  lb-server:
    build: ./lb-server
    ports:
      - "4200:4200"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app-network
    restart: always


  server1:
    build: ./server1
    ports:
      - "4300:4300"
    networks:
      - app-network

  server2:
    build: ./server2
    ports:
      - "4400:4400"
    networks:
      - app-network

  server3:
    build: ./server3
    ports:
      - "4500:4500"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge